version: '3.9'

services:
  app-dev:
    build:
      context: ./app
      dockerfile: Dockerfile  # DEV file
    ports:
      - 3000:3000
    depends_on:
      - db
    environment:
      COMMIT_ID: ${COMMIT_ID:-unknown_env}
      MAILGUN_API: ${MAILGUN_API}
      MAPS_API: ${MAPS_API}

  db:
    image: postgres:alpine
    ports:
      - 5432:5432
    volumes:
      - ./db/dev/:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: aapi
      POSTGRES_HOST_AUTH_METHOD: trust
